global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'datacenter', 'app']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 30s
  receiver: 'slack-notifications'
receivers:
- name: 'slack-notifications'
  slack_configs:
  - text: 'sample text'
    api_url: your incoming webhook'
