version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
      - './.volumes/prometheus:/prometheus'
  web:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    entrypoint: nginx-prometheus-exporter -nginx.scrape-uri=http://localhost:80/nginx_status
    ports:
      - "9113:9113"
    pid: "service:web"
networks:
  default:
    ipam:
      config:
        - subnet: 172.22.0.0/16
