global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s # global.scrape_intervalを上書き
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "web"
    scrape_interval: 5s
    static_configs:
      - targets: ["nginx-exporter:9113"]

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
