FROM node:21-alpine3.19 as builder

WORKDIR /app

RUN corepack enable

COPY package.json package-lock.json pnpm-lock.yaml ./
RUN pnpm install --prod --frozen-lockfile

COPY . .

ENV NODE_ENV=production

RUN pnpm run build

FROM node:21-alpine3.19 as runner

WORKDIR /app

COPY --from=builder /app/package.json /app/package-lock.json /app/pnpm-lock.yaml ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

USER node

EXPOSE 3000

CMD ["pnpm", "start"]
